version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: ctl-test-node
    ports:
      - '3002:3002'
    volumes:
      - .:/home/node/app

  db:
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ctl-test

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '9000:80'
    depends_on:
      - db
